spring.application.name=dine-in-order-api
spring.datasource.url=mysql://localhost:3306/dine_in_order_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true